source("code/data_merge_functions.R")
library(composr)

# Make sure to source hte first 27 lines of preliminary weighted analysis to get
# data, quesitonnaire, choices and weighting function

mydata$date <- gsub("-","",data$arrive_libya)
mydata <- mydata %>% new_recoding(target = time_arrival_category, source = date ) %>%
  recode_to("0_2_year", where.num.larger.equal =  "20170801") %>%
  recode_to("2_4_year", where.num.smaller = "20170801") %>%
  recode_to("4_6_year", where.num.smaller = "20150801") %>%
  recode_to("6_8_year", where.num.smaller = "20130801") %>%
  recode_to("over_8years", where.num.smaller = "20110801") %>%
  end_recoding()

mydata <- mydata %>% new_recoding(facing_barriers_acccess_marketplace) %>%
  recode_to("no",
            where =  sm_selected(barriers_access_market, exactly = c("no_barriers_access_market"))) %>%
  recode_to("yes",
            where = sm_selected(barriers_access_market, none = c("no_barriers_access_market"))) %>%
  recode_to("dk_dwta",
            where = sm_selected(barriers_access_market, any = c("dk", "dwta"))) %>%
  end_recoding()


mydata <- mydata %>%
  mutate(fcs = (cereals * 2) + (legumes * 3) + veggies + fruits + (meat * 4) + (dairy * 4) + (fats * 0.5) + (sugar * 0.5),
         fcs_category = case_when(
           fcs <= 28 ~ "poor",
           fcs > 28 & fcs <= 42 ~ "borderline",
           fcs > 42 ~ "acceptable"
         ),
         rcsi = less_expensive_quality + (borrow_relatives * 2) + reduce_number_meals + (reduce_adult * 3) + shrink_meals,
         rcsi_category = case_when(
           rcsi <= 3 ~ "low",
           rcsi > 3 & rcsi <= 9 ~ "medium",
           rcsi > 9 ~ "high"
         ),
         cash_coping_stress = rowSums(select(., 
                                             sold_nonproductive_hh_assets,
                                             spent_savings,
                                             borrowed_purchased_oncredit_food,
                                             reduced_expenditures_essential_nfi) %>%
                                        mutate_all(~ .x %in% c("no_already_exhausted", "yes")),
                                      na.rm = T),
         cash_coping_crisis = rowSums(select(., 
                                             sold_productive_hh_assets,
                                             borrowed_money,
                                             reduced_expenditures_health_education,
                                             took_additional_job) %>%
                                        mutate_all(~ .x %in% c("no_already_exhausted", "yes")),
                                      na.rm = T),
         cash_coping_emergency = rowSums(select(., 
                                                begging,
                                                adult_accepting_degrading_illegal_work,
                                                minor_accepting_degrading_illegal_work,
                                                child_marriage) %>%
                                           mutate_all(~ .x %in% c("no_already_exhausted", "yes")),
                                         na.rm = T),
         cash_coping = case_when(
           cash_coping_emergency > 0 ~ "emergency",
           cash_coping_crisis > 0 ~ "crisis",
           cash_coping_stress > 0 ~ "stress",
           cash_coping_emergency + cash_coping_crisis + cash_coping_stress == 0 ~ "none"
           
         ),
         engaging_agriculture_production = ifelse(agricultural_production.yes_crop_production == 1 |
                                                  agricultural_production.yes_livestock_production == 1 |
                                                  agricultural_production.yes_fishing == 1, "yes", "no"),
         
         food_expenditure_exc_0 = ifelse(food_expenditure ==0,NA,food_expenditure),
         rent_expenditure_exc_0 = ifelse(rent_expenditure ==0,NA,rent_expenditure),
         shelter_maintenance_expenditure_exc_0 = ifelse(shelter_maintenance_expenditure ==0,NA,shelter_maintenance_expenditure),
         water_expenditure_exc_0 = ifelse(water_expenditure ==0,NA,water_expenditure),
         nfi_expenditure_exc_0 = ifelse(nfi_expenditure ==0,NA,nfi_expenditure),
         utilities_expenditure_exc_0 = ifelse(utilities_expenditure ==0,NA,utilities_expenditure),
         fuel_expenditure_exc_0 = ifelse(fuel_expenditure ==0,NA,fuel_expenditure),
         health_related_expenditure_exc_0 = ifelse(health_related_expenditure ==0,NA,health_related_expenditure),
         education_related_expenditure_exc_0 = ifelse(education_related_expenditure ==0,NA,education_related_expenditure),
         transportation_expenditure_exc_0 = ifelse(transportation_expenditure ==0,NA,transportation_expenditure),
         mobile_phone_credit_expenditure_exc_0 = ifelse(mobile_phone_credit_expenditure ==0,NA,mobile_phone_credit_expenditure),
         productive_assets_expenditure_exc_0 = ifelse(productive_assets_expenditure ==0,NA,productive_assets_expenditure),
         debt_repayment_expenditure_exc_0 = ifelse(debt_repayment_expenditure ==0,NA,debt_repayment_expenditure),
         other_expenditure_exc_0 = ifelse(other_expenditure ==0,NA,other_expenditure),
         
         total_expenditures = rowSums(select(.,food_expenditure,rent_expenditure,shelter_maintenance_expenditure,
                                             water_expenditure,
                                             nfi_expenditure,
                                             utilities_expenditure,
                                             fuel_expenditure,health_related_expenditure,education_related_expenditure
                                             ,transportation_expenditure,mobile_phone_credit_expenditure,
                                             productive_assets_expenditure,
                                             debt_repayment_expenditure,other_expenditure)
                                      , na.rm=T),
         total_expenditures_exc_0 = ifelse(total_expenditures == 0, NA, total_expenditures),
         spending_65_onfood = ifelse(food_expenditure_exc_0/total_expenditures_exc_0 >=0.65, "yes","no"),
         
         substandard_shelter = ifelse(shelter_type %in% c("unfinished_rooms","public_building_not_used_for_shelter",
                                                          "connection_house","private_building_not_used_for_shelter",
                                                          "camp_informal_settlement","temporary_shelter_ngos",
                                                          "outdoors","tent_caravan"),"yes","no"),
         
         school_aged_children = school_aged_boys + school_aged_girls,
         attending_school_male = rowSums(select(., attending_boys_6_10,attending_boys_11_17)),
         attending_school_female = rowSums(select(.,attending_girls_6_10,attending_girls_11_17)),
         total_attending_school = rowSums(select(.,attending_boys_6_10,attending_boys_11_17,
                                                 attending_girls_6_10,attending_girls_11_17)),
         signs_psychological_distress = ifelse(sm_selected(psycho_distress,any = c("none_psycho_distress","dwta")),
                                               "no","yes"),
         children_labour = ifelse(migrant_child_labour %in% c("no","dk","dwta"), "no","yes"),
         
         sold_nonproductive_hh_assets_t_f = sold_nonproductive_hh_assets %in% c("yes","no_already_exhausted"),
         sold_productive_hh_assets_t_f = sold_productive_hh_assets %in% c("yes","no_already_exhausted"),
         spent_savings_t_f = spent_savings %in% c("yes","no_already_exhausted"),
         borrowed_money_t_f = borrowed_money %in% c("yes","no_already_exhausted"),
         borrowed_purchased_oncredit_food_t_f = borrowed_purchased_oncredit_food %in% c("yes","no_already_exhausted"),
         reduced_expenditures_essential_nfi_t_f = reduced_expenditures_essential_nfi %in% c("yes","no_already_exhausted"),
         reduced_expenditures_health_education_t_f = reduced_expenditures_health_education %in% c("yes","no_already_exhausted"),
         child_dropped_school_t_f = child_dropped_school %in% c("yes","no_already_exhausted"),
         delayed_skipped_rent_t_f = delayed_skipped_rent %in% c("yes","no_already_exhausted"),
         begging_t_f = begging %in% c("yes","no_already_exhausted"),
         took_additional_job_t_f = took_additional_job %in% c("yes","no_already_exhausted"),
         adult_accepting_degrading_illegal_work_t_f = adult_accepting_degrading_illegal_work %in% c("yes","no_already_exhausted"),
         minor_accepting_degrading_illegal_work_t_f = minor_accepting_degrading_illegal_work %in% c("yes","no_already_exhausted"),
         child_marriage_t_f = child_marriage %in% c("yes","no_already_exhausted"),
         
         livelihood_coping = str_concat("yes","no_already_exhausted",
                                        sold_nonproductive_hh_assets,
                                        sold_productive_hh_assets,
                                        spent_savings,
                                        borrowed_money,
                                        borrowed_purchased_oncredit_food,
                                        reduced_expenditures_essential_nfi,
                                        reduced_expenditures_health_education,
                                        child_dropped_school,
                                        delayed_skipped_rent,
                                        begging,
                                        took_additional_job,
                                        adult_accepting_degrading_illegal_work,
                                        minor_accepting_degrading_illegal_work,
                                        child_marriage),
         livelihood_coping_without_na = ifelse(is.na(livelihood_coping),"no",livelihood_coping),
         hh_with_school_aged_children = ifelse(rowSums(select(.,school_aged_boys,school_aged_girls),na.rm = T)>0,
                                               "yes","no"),
         
         livelihood_coping_mechanism = rowSums(select(.,sold_nonproductive_hh_assets:child_marriage) %>%
                                                 mutate_all(~.x %in% c("already_exhausted_this_coping_strategy", "yes")),
                                               na.rm = T),
         
         permanent_job_adult = rowSums(select(., permanent_job_adult_male, permanent_job_adult_female), na.rm = T),
         temporary_job_adult = rowSums(select(., temporary_job_adult_male, temporary_job_adult_female), na.rm = T),
         daily_labour_job_adult = rowSums(select(., daily_labour_adult_male, daily_labour_adult_female), na.rm = T),
         gvt_payroll_job_adult = rowSums(select(., gvt_payroll_adult_male, gvt_payroll_adult_female), na.rm = T),
         other_job_adult_adult = rowSums(select(., other_job_adult_male, other_job_adult_female), na.rm = T),
         
         gvt_public_sector_adult = rowSums(select(., gvt_public_sector_male, gvt_public_sector_female), na.rm = T),
         libyan_owned_business_adult = rowSums(select(., libyan_owned_business_male, libyan_owned_business_female), na.rm = T),
         foreign_owned_business_adult = rowSums(select(., foreign_owned_business_male, foreign_owned_business_female), na.rm = T),
         libyan_ngos_csos_adult = rowSums(select(., libyan_ngos_csos_male, libyan_ngos_csos_female), na.rm = T),
         international_ngos_adult = rowSums(select(., international_ngos_male, international_ngos_female), na.rm = T),
         own_family_business_adult = rowSums(select(., own_family_business_male, own_family_business_female), na.rm = T),
         informal_irregular_labour_adult = rowSums(select(., informal_irregular_labour_male, informal_irregular_labour_female), na.rm = T),
         other_institution_adult = rowSums(select(., other_institution_male, other_institution_female), na.rm = T),
         
         gvt_salary_without_0 = ifelse(gvt_salary==0, NA, gvt_salary),
         gvt_social_benefits_without_0 = ifelse(gvt_social_benefits==0, NA, gvt_social_benefits),
         non_gvt_salary_without_0 = ifelse(non_gvt_salary==0, NA, non_gvt_salary),
         casual_labour_without_0 = ifelse(casual_labour==0, NA, casual_labour),
         own_business_income_without_0 = ifelse(own_business_income==0, NA, own_business_income),
         remittances_without_0 = ifelse(remittances==0, NA, remittances),
         family_support_without_0 = ifelse(family_support==0, NA, family_support),
         humanitarian_assistance_without_0 = ifelse(humanitarian_assistance==0, NA, humanitarian_assistance),
         zakat_without_0 = ifelse(zakat==0, NA, zakat),
         income_other_without_0 = ifelse(income_other==0, NA, income_other),
         
         food_expenditure_without_0 = ifelse(food_expenditure==0, NA, food_expenditure),
         rent_expenditure_without_0 = ifelse(rent_expenditure==0, NA, rent_expenditure),
         shelter_maintenance_expenditure_without_0 = ifelse(shelter_maintenance_expenditure==0, NA, shelter_maintenance_expenditure),
         water_expenditure_without_0 = ifelse(water_expenditure==0, NA, water_expenditure),
         nfi_expenditure_without_0 = ifelse(nfi_expenditure==0, NA, nfi_expenditure),
         utilities_expenditure_without_0 = ifelse(utilities_expenditure==0, NA, utilities_expenditure),
         fuel_expenditure_without_0 = ifelse(fuel_expenditure==0, NA, fuel_expenditure),
         health_related_expenditure_without_0 = ifelse(health_related_expenditure==0, NA, health_related_expenditure),
         education_related_expenditure_without_0 = ifelse(education_related_expenditure==0, NA, education_related_expenditure),
         transportation_expenditure_without_0 = ifelse(transportation_expenditure==0, NA, transportation_expenditure),
         mobile_phone_credit_expenditure_without_0 = ifelse(mobile_phone_credit_expenditure==0, NA, mobile_phone_credit_expenditure),
         productive_assets_expenditure_without_0 = ifelse(productive_assets_expenditure==0, NA, productive_assets_expenditure),
         debt_repayment_expenditure_without_0 = ifelse(debt_repayment_expenditure==0, NA, debt_repayment_expenditure),
         other_expenditure_without_0 = ifelse(other_expenditure==0, NA, other_expenditure),
         
         rental_cost_without_0 = ifelse(rental_cost==0, NA, rental_cost),
         hh_total_debt_without_0 = ifelse(hh_total_debt==0, NA, hh_total_debt),
         bank_withdrawal_amount_without_0 = ifelse(bank_withdrawal_amount==0, NA, bank_withdrawal_amount),
         
         permanent_job_minor = rowSums(select(., permanent_job_minor_male, permanent_job_minor_female), na.rm = T),
         temporary_job_minor = rowSums(select(., temporary_job_minor_male, temporary_job_minor_female), na.rm = T),
         daily_labour_job_minor = rowSums(select(., daily_labour_minor_male, daily_labour_minor_female), na.rm = T),
         nb_hectares_cultivated_less1ha= case_when(
           nb_hectares_cultivated <= 1 ~ "yes",
           nb_hectares_cultivated > 1 ~ "no"),
         lcs = case_when(
           cash_coping == "none" ~ 1,
           cash_coping == "stress" ~ 2,
           cash_coping == "crisis" ~ 3,
           cash_coping == "emergency" ~ 4
         ),
         
         fsi = (0.5 * fcs_index) + (0.25 * foodexp) + (0.25 * lcs),
           
         atleast_one_crisis_emergency_cash_coping= ifelse(cash_coping %in% c("crisis","emergency"),"yes","no"),
         nfi_need = rowSums(select(., mattresses:construction_materials_equipment,
                                   -ends_with("_other")) %>%
                              mutate_all(~ .x %in% c("hh_doesnt_own_it", "hh_owns_it_need_more")),
                            na.rm = T),
         nfi_need = ifelse(nfi_need >= 8, "has_nfi_need", "no_need"),
         bottle_fed_child = ifelse(fed_children_bottled_milk > 0 , "bottle_fed_child", "no_bottle_feeding"),
         unable_vaccinate = ifelse(nb_children_notable_get_vaccination > 0, "unable_vaccinate", "able_vaccinate"),
         nb_youth_male_edu = ifelse(nb_youth_male == 0, NA, nb_youth_male), ######## these vars allow for weighting on enrollment data
         nb_children_male_edu = ifelse(nb_children_male == 0, NA, nb_children_male),
         nb_youth_female_edu = ifelse(nb_youth_female == 0, NA, nb_youth_female),
         nb_children_female_edu = ifelse(nb_children_female == 0, NA, nb_children_female),
         enrolled_school_female_15_17_edu = ifelse(enrolled_school_female_15_17 == 0, NA, enrolled_school_female_15_17), ## These vars allow for weighting attendance data
         enrolled_school_female_6_14_edu = ifelse(enrolled_school_female_6_14 == 0, NA, enrolled_school_female_6_14),
         enrolled_school_male_15_17_edu = ifelse(enrolled_school_male_15_17 == 0, NA, enrolled_school_male_15_17),
         enrolled_school_male_6_14_edu = ifelse(enrolled_school_male_6_14 == 0, NA, enrolled_school_male_6_14),
         attended_school_female_15_17_edu = ifelse(attended_school_female_15_17 == 0, NA, attended_school_female_15_17), ## These vars allow for weighting attendance data
         attended_school_female_6_14_edu = ifelse(attended_school_female_6_14 == 0, NA, attended_school_female_6_14),
         attended_school_male_15_17_edu = ifelse(attended_school_male_15_17 == 0, NA, attended_school_male_15_17),
         attended_school_male_6_14_edu = ifelse(attended_school_male_6_14 == 0, NA, attended_school_male_6_14),
         document_needs = str_concat("not_everyone_has_legal_doc",
                                     property_docs,
                                     family_books,
                                     certificate_nationality,
                                     passport,
                                     national_identifier,
                                     national_idcard,
                                     residence_certificate,
                                     birth_certificate,
                                     other_docs),
         lost_docs = ifelse(is.na(document_needs), "no", "yes"),
         lost_docs_conflict = ifelse(rowSums(select(.,property_docs_lost:other_docs_lost) %>% 
                                               mutate_all(~.x %in% c("lost_doc_conflict")),na.rm = T) > 0, "yes","no"),
         not_having_doc_reasons = str_concat(c("mahalla_unable_issue_doc", "unable_obtain_doc","lost_doc_conflict"),
                                             property_docs_lost,
                                             family_books_lost,
                                             certificate_nationality_lost,
                                             passport_lost,
                                             national_identifier_lost,
                                             national_idcard_lost,
                                             residence_certificate_lost,
                                             birth_certificate_lost,
                                             other_docs_lost),
           
         #loss_doc_impact = ifelse(sm_selected(losing_legal_docs_impact, any = c("losing_docs_no_impact","dk","dwta")),NA_character_,losing_legal_docs_impact),
         #modality_ass_received = ifelse(sm_selected(modality_assistance_received, any = c("dk","dwta")),NA_character_,modality_assistance_received),
         #humanitarian_ass_barriers = ifelse(sm_selected(humanitarian_assistance_barriers, any = c("no_barriers_humanitarian_assistance","dk","dwta")),NA_character_,humanitarian_assistance_barriers),
         returnee_issues = str_concat("yes",
                                      house_occupied,
                                      inability_prove_legal_ownership,
                                      hostility_from_local_community,
                                      lack_security_area,
                                      parts_house_property_destroyed,
                                      missing_valuables_house_property,
                                      inability_move_freely,
                                      basic_services_hh_nolonger_working,
                                      basic_services_community_nolonger_working,
                                      mobilephone_network_nolonger_working,
                                      other_problem_faced),
         returnee_issues = ifelse(is.na(returnee_issues) & displacement_status == "returnee",
                                  "",
                                  returnee_issues)) %>% mutate(
          total_income_without_0 = ifelse(total_income ==0, NA, total_income),
          total_expenditure_without_0 = ifelse(total_expenditures ==0, NA, total_expenditures),
          
          working_minors= rowSums(select(.,permanent_job_minor, daily_labour_job_minor, temporary_job_minor), na.rm=T),
          working_minors_male= rowSums(select(.,permanent_job_minor_male, daily_labour_minor_male, temporary_job_minor_male), na.rm=T),
          working_minors_female= rowSums(select(.,permanent_job_minor_female, daily_labour_minor_female, temporary_job_minor_female), na.rm=T),
          enrolled_school_female_edu = rowSums(select(.,  enrolled_school_female_15_17_edu,
                                                          enrolled_school_female_6_14_edu), na.rm = T),
          enrolled_school_male_edu = rowSums(select(.,    enrolled_school_male_15_17_edu,
                                                          enrolled_school_male_6_14_edu), na.rm = T),
          attended_school_male = rowSums(select(., attended_school_male_6_14_edu,
                                                attended_school_male_15_17_edu), na.rm = T),
          attended_school_female = rowSums(select(.,  attended_school_female_6_14_edu,
                                                  attended_school_female_15_17_edu), na.rm = T),
          nb_male_edu = rowSums(select(.,   nb_youth_male_edu,
                                            nb_children_male_edu), na.rm = T),
          nb_female_edu = rowSums(select(., nb_youth_female_edu,
                                             nb_children_female_edu), na.rm = T)) %>% mutate(
          school_age_children = rowSums(select(., nb_male_edu,
                                               nb_female_edu), na.rm = T),
          enrolled_school = rowSums(select(., enrolled_school_female_edu,
                                              enrolled_school_male_edu), na.rm = T),
          attended_school = rowSums(select(., attended_school_male,
                                              attended_school_female), na.rm = T),
          notattending_notenrolled_school = rowSums(select(.,notattending_notenrolled_school_male,
                                                           notattending_notenrolled_school_female),
                                                    na.rm = T),
          not_attending_since_less_1month = rowSums(select(.,not_attending_since_less_1month_male,
                                                           not_attending_since_less_1month_female),
                                                    na.rm = T),
          not_attending_since_1_3months = rowSums(select(.,not_attending_since_1_3months_female,
                                                              not_attending_since_1_3months_female),
                                                    na.rm = T),
          not_attending_since_4_6months = rowSums(select(.,not_attending_since_4_6months_male,
                                                         not_attending_since_4_6months_female),
                                                  na.rm = T),
          not_attending_since_more_6months = rowSums(select(.,not_attending_since_more_6months_male,
                                                            not_attending_since_more_6months_female),
                                                  na.rm = T),
          not_attending_since_entire_schoolyear = rowSums(select(.,not_attending_since_entire_schoolyear_male,
                                                                 not_attending_since_entire_schoolyear_female),
                                                     na.rm = T),
          children_nonformal_edu = case_when(
            sm_selected(nonformal_education,exactly = c("no")) ~ "no",
            sm_selected(nonformal_education,any = c("yes_nonformal_classes_byschool",
                                                    "yes_nonformal_classes_bycommunity",
                                                    "yes_nonformal_privatebusiness",
                                                    "yes_selflearning",
                                                    "yes_assistance_ngos")) ~ "yes")
          ) %>%
  rowwise() %>%
  mutate(no_daily_difficulty = sum(no_difficulty_carrying_activities_female_adults,
                                   no_difficulty_carrying_activities_female_infant,
                                   no_difficulty_carrying_activities_female_children,
                                   no_difficulty_carrying_activities_female_youth,
                                   no_difficulty_carrying_activities_female_elderly,
                                   no_difficulty_carrying_activities_male_adults,
                                   no_difficulty_carrying_activities_male_infant,
                                   no_difficulty_carrying_activities_male_children,
                                   no_difficulty_carrying_activities_male_youth,
                                   no_difficulty_carrying_activities_male_elderly,
                                   na.rm = T),
         minor_daily_difficulty = sum(minor_difficulties_carrying_activities_female_adults,
                                      minor_difficulties_carrying_activities_female_infant,
                                      minor_difficulties_carrying_activities_female_children,
                                      minor_difficulties_carrying_activities_female_youth,
                                      minor_difficulties_carrying_activities_female_elderly,
                                      minor_difficulties_carrying_activities_male_adults,
                                      minor_difficulties_carrying_activities_male_infant,
                                      minor_difficulties_carrying_activities_male_children,
                                      minor_difficulties_carrying_activities_male_youth,
                                      minor_difficulties_carrying_activities_male_elderly,
                                      na.rm = T),
         daily_needs_assistance = sum(some_difficulties_carrying_activities_female_adults,
                                      some_difficulties_carrying_activities_female_infant,
                                      some_difficulties_carrying_activities_female_children,
                                      some_difficulties_carrying_activities_female_youth,
                                      some_difficulties_carrying_activities_female_elderly,
                                      some_difficulties_carrying_activities_male_adults,
                                      some_difficulties_carrying_activities_male_infant,
                                      some_difficulties_carrying_activities_male_children,
                                      some_difficulties_carrying_activities_male_youth,
                                      some_difficulties_carrying_activities_male_elderly,
                                      alot_difficulties_carrying_activities_female_adults,
                                      alot_difficulties_carrying_activities_female_infant,
                                      alot_difficulties_carrying_activities_female_children,
                                      alot_difficulties_carrying_activities_female_youth,
                                      alot_difficulties_carrying_activities_female_elderly,
                                      alot_difficulties_carrying_activities_male_adults,
                                      alot_difficulties_carrying_activities_male_infant,
                                      alot_difficulties_carrying_activities_male_children,
                                      alot_difficulties_carrying_activities_male_youth,
                                      alot_difficulties_carrying_activities_male_elderly,
                                      cannot_carry_activities_female_adults,
                                      cannot_carry_activities_female_infant,
                                      cannot_carry_activities_female_children,
                                      cannot_carry_activities_female_youth,
                                      cannot_carry_activities_female_elderly,
                                      cannot_carry_activities_male_adults,
                                      cannot_carry_activities_male_infant,
                                      cannot_carry_activities_male_children,
                                      cannot_carry_activities_male_youth,
                                      cannot_carry_activities_male_elderly,
                                      na.rm = T),
         total_assistance = sum(no_daily_difficulty, minor_daily_difficulty, daily_needs_assistance)) %>%
  ungroup
