# Ready to summarize all our data
# PLEASE! Remember to source the data, questionnaire, choices, and weights from preliminary_weighted_analysis.R
source("code/data_merge_prep.R")

  dm_mantika_data <-  mydata %>%
  group_by(mantika_label) %>%
  summarize(
    nb_respondents = n(),
    family_size = meanR(hh_size,.),
    female_respondent = percent_response(respondent_gender,.,"female"),
    nb_children = meanR(nb_under18,.),
    
    duration_stay_0_2years = percent_response(time_arrival_category,.,"0_2_year"),
    duration_stay_2_4years = percent_response(time_arrival_category,.,"2_4_year"),
    duration_stay_4_6years = percent_response(time_arrival_category,.,"4_6_year"),
    duration_stay_6_8years = percent_response(time_arrival_category,.,"6_8_year"),
    duration_stay_over_8years = percent_response(time_arrival_category,.,"over_8years"),
    
    pct_mena = percent_response(region_of_origin,.,"mena"),
    pct_w_c_africa = percent_response(region_of_origin,.,"w_c_africa"),
    pct_e_africa = percent_response(region_of_origin,.,"e_africa"),
    pct_other_region_origin = percent_response(region_of_origin,.,"other"),
    
    fcs_poor = percent_response(fcs_category,.,"poor"),
    fcs_borderline = percent_response(fcs_category,.,"borderline"),
    fcs_acceptable = percent_response(fcs_category,.,"acceptable"),
    lcsi_none = percent_response(cash_coping,.,"none"),
    lcsi_stress = percent_response(cash_coping,.,"stress"),
    lcsi_crisis = percent_response(cash_coping,.,"crisis"),
    lcsi_emergency = percent_response(cash_coping,.,"emergency"),
    
    food_source_1_name = select_percents(food_source,1,.,questions,choices,"label"),
    food_source_1_pct = select_percents(food_source,1,.,questions,choices,"percent"),
    food_source_2_name = select_percents(food_source,2,.,questions,choices,"label"),
    food_source_2_pct = select_percents(food_source,2,.,questions,choices,"percent"),
    food_source_3_name = select_percents(food_source,3,.,questions,choices,"label"),
    food_source_3_pct = select_percents(food_source,3,.,questions,choices,"percent"),
    agriculture_production = percent_response(engaging_agriculture_production,.,"yes"),
    
    rely_less_preferred_food = meanR(less_expensive_quality,.),
    borrow_food = meanR(borrow_relatives,.),
    reduce_nb_meals_day = meanR(reduce_number_meals,.),
    reduce_portion = meanR(shrink_meals,.),
    reduce_portion_adult = meanR(reduce_adult,.),
    rcsi_low = percent_response(rcsi_category,.,"low"),
    rcsi_medium = percent_response(rcsi_category,.,"medium"),
    rcsi_high = percent_response(rcsi_category,.,"high"),
    spending_65_onfood_pct = percent_response(spending_65_onfood,.,"yes"),
    
    livelihood_coping_strategy_1_name = select_percents(livelihood_coping_without_na,1,.,questions,choices,"label"),
    livelihood_coping_strategy_1_pct = select_percents(livelihood_coping_without_na,1,.,questions,choices,"percent"),
    livelihood_coping_strategy_2_name = select_percents(livelihood_coping_without_na,2,.,questions,choices,"label"),
    livelihood_coping_strategy_2_pct = select_percents(livelihood_coping_without_na,2,.,questions,choices,"percent"),
    livelihood_coping_strategy_3_name = select_percents(livelihood_coping_without_na,3,.,questions,choices,"label"),
    livelihood_coping_strategy_3_pct = select_percents(livelihood_coping_without_na,3,.,questions,choices,"percent"),
    livelihood_coping_strategy_4_name = select_percents(livelihood_coping_without_na,4,.,questions,choices,"label"),
    livelihood_coping_strategy_4_pct = select_percents(livelihood_coping_without_na,4,.,questions,choices,"percent"),
    livelihood_coping_strategy_5_name = select_percents(livelihood_coping_without_na,5,.,questions,choices,"label"),
    livelihood_coping_strategy_5_pct = select_percents(livelihood_coping_without_na,5,.,questions,choices,"percent"),
  
    
    lcs_reason_1_name = select_percents(using_cash_coping_mechanism_reasons,1,.,questions,choices,"label"),
    lcs_reason_1_pct = select_percents(using_cash_coping_mechanism_reasons,1,.,questions,choices,"percent"),
    lcs_reason_2_name = select_percents(using_cash_coping_mechanism_reasons,2,.,questions,choices,"label"),
    lcs_reason_2_pct = select_percents(using_cash_coping_mechanism_reasons,2,.,questions,choices,"percent"),
    lcs_reason_3_name = select_percents(using_cash_coping_mechanism_reasons,3,.,questions,choices,"label"),
    lcs_reason_3_pct = select_percents(using_cash_coping_mechanism_reasons,3,.,questions,choices,"percent"),
    
    drinking_water_distance_0_100m = percent_response(distance_drinkingwater,.,"upto_100m"),
    drinking_water_distance_101_200m = percent_response(distance_drinkingwater,.,"between_101_200m"),
    drinking_water_distance_201_300m = percent_response(distance_drinkingwater,.,"between_201_300m"),
    drinking_water_distance_301_400m = percent_response(distance_drinkingwater,.,"between_301_400m"),
    drinking_water_distance_401_500m = percent_response(distance_drinkingwater,.,"between_401_500m"),
    drinking_water_distance_more_500m = percent_response(distance_drinkingwater,.,"more_500m"),
    
    unsufficient_drinkingwater = percent_response(unsufficient_quantity_water,.,"yes"),
    no_water_treatment = percent_response(water_treatment,.,"no_treatment_used"),
    
    source_drinkingwater_1_name = select_percents(primary_drinkingwater_source,1,.,questions,choices,"label"),
    source_drinkingwater_1_pct = select_percents(primary_drinkingwater_source,1,.,questions,choices,"percent"),
    source_drinkingwater_2_name = select_percents(primary_drinkingwater_source,2,.,questions,choices,"label"),
    source_drinkingwater_2_pct = select_percents(primary_drinkingwater_source,2,.,questions,choices,"percent"),
    source_drinkingwater_3_name = select_percents(primary_drinkingwater_source,3,.,questions,choices,"label"),
    source_drinkingwater_3_pct = select_percents(primary_drinkingwater_source,3,.,questions,choices,"percent"),
    
    toilet_type_1_name = select_percents(toilet_type,1,.,questions,choices,"label"),
    toilet_type_1_pct = select_percents(toilet_type,1,.,questions,choices,"percent"),
    toilet_type_2_name = select_percents(toilet_type,2,.,questions,choices,"label"),
    toilet_type_2_pct = select_percents(toilet_type,2,.,questions,choices,"percent"),
    toilet_type_3_name = select_percents(toilet_type,3,.,questions,choices,"label"),
    toilet_type_3_pct = select_percents(toilet_type,3,.,questions,choices,"percent"),
    
    water_quality_fine = meanR(drinkingwater_quality.water_fine_todrink,.),
    water_quality_not_good = meanR(drinkingwater_quality.water_taste_notgood,.),
    water_quality_smell_notgood = meanR(drinkingwater_quality.water_smell_notgood,.),
    water_quality_discolored = meanR(drinkingwater_quality.water_discloured,.),
    water_quality_causes_healthissues = meanR(drinkingwater_quality.water_causes_health_issues,.),
    water_quality_dk = meanR(drinkingwater_quality.dk,.),
    
    facing_challenges_healthcare = percent_response(access_healthcare_challenges,.,"yes"),
    gavebirth_2years = percent_response(gave_birth_2years,.,"yes"),
    
    healthcare_challenges_mena = percent_response(filter(.,region_of_origin=="mena")[["access_healthcare_challenges"]],
                                                  filter(.,region_of_origin=="mena"),
                                                  "yes",
                                                  group = !!get_group(.)),
    healthcare_challenges_w_c_africa = percent_response(filter(.,region_of_origin=="w_c_africa")[["access_healthcare_challenges"]],
                                                  filter(.,region_of_origin=="w_c_africa"),
                                                  "yes",
                                                  group = !!get_group(.)),
    healthcare_challenges_e_africa = percent_response(filter(.,region_of_origin=="e_africa")[["access_healthcare_challenges"]],
                                                        filter(.,region_of_origin=="e_africa"),
                                                        "yes",
                                                        group = !!get_group(.)),
    healthcare_challenges_other_region_origin = percent_response(filter(.,region_of_origin=="other")[["access_healthcare_challenges"]],
                                                      filter(.,region_of_origin=="other"),
                                                      "yes",
                                                      group = !!get_group(.)),
    
    barriers_healthcare_1_name = select_percents(access_healthcare_challenges_reasons,1,.,questions,choices,"label"),
    barriers_healthcare_1_pct = select_percents(access_healthcare_challenges_reasons,1,.,questions,choices,"percent"),
    barriers_healthcare_2_name = select_percents(access_healthcare_challenges_reasons,2,.,questions,choices,"label"),
    barriers_healthcare_2_pct = select_percents(access_healthcare_challenges_reasons,2,.,questions,choices,"percent"),
    barriers_healthcare_3_name = select_percents(access_healthcare_challenges_reasons,3,.,questions,choices,"label"),
    barriers_healthcare_3_pct = select_percents(access_healthcare_challenges_reasons,3,.,questions,choices,"percent"),
    barriers_healthcare_4_name = select_percents(access_healthcare_challenges_reasons,4,.,questions,choices,"label"),
    barriers_healthcare_4_pct = select_percents(access_healthcare_challenges_reasons,4,.,questions,choices,"percent"),
    barriers_healthcare_5_name = select_percents(access_healthcare_challenges_reasons,5,.,questions,choices,"label"),
    barriers_healthcare_5_pct = select_percents(access_healthcare_challenges_reasons,5,.,questions,choices,"percent"),
    barriers_healthcare_6_name = select_percents(access_healthcare_challenges_reasons,6,.,questions,choices,"label"),
    barriers_healthcare_6_pct = select_percents(access_healthcare_challenges_reasons,6,.,questions,choices,"percent"),
    barriers_healthcare_7_name = select_percents(access_healthcare_challenges_reasons,7,.,questions,choices,"label"),
    barriers_healthcare_7_pct = select_percents(access_healthcare_challenges_reasons,7,.,questions,choices,"percent"),
    barriers_healthcare_8_name = select_percents(access_healthcare_challenges_reasons,8,.,questions,choices,"label"),
    barriers_healthcare_8_pct = select_percents(access_healthcare_challenges_reasons,8,.,questions,choices,"percent"),
    barriers_healthcare_9_name = select_percents(access_healthcare_challenges_reasons,9,.,questions,choices,"label"),
    barriers_healthcare_9_pct = select_percents(access_healthcare_challenges_reasons,9,.,questions,choices,"percent"),
    
    travel_healthcare_facility_less15min = percent_response(travel_to_healthcare_provider,.,"less_15min"),
    travel_healthcare_facility_15_29min = percent_response(travel_to_healthcare_provider,.,"between_15_29min"),
    travel_healthcare_facility_30_59min = percent_response(travel_to_healthcare_provider,.,"between_30_59min"),
    travel_healthcare_facility_1_2h = percent_response(travel_to_healthcare_provider,.,"between_1_2hours"),
    travel_healthcare_facility_more2h = percent_response(travel_to_healthcare_provider,.,"more_2hours"),
    
    #suffer_chronicdisease =  percent_response(suffer_chronicdisease,.,"yes"),
    suffer_chronicdisease =  count_response(suffer_chronicdisease,.,"yes"),
    healthcare_challenges_male = percent_response(filter(.,respondent_gender=="male")[["access_healthcare_challenges"]],
                                                  filter(.,respondent_gender=="male"),
                                                  "yes",
                                                  group = !!get_group(.)),
    healthcare_challenges_female = percent_response(filter(.,respondent_gender=="female")[["access_healthcare_challenges"]],
                                                  filter(.,respondent_gender=="female"),
                                                  "yes",
                                                  group = !!get_group(.)),
    signs_psycho_distress = percent_response(signs_psychological_distress,.,"yes"),
    
    
    physical_cognitive_no_difficulties = percent_response(physical_cognitive_difficulties_category,.,"no_difficulty_carrying_activities_male_infant"),
    physical_cognitive_minor_difficulties = percent_response(physical_cognitive_difficulties_category,.,"minor_difficulties_carrying_activities_male_infant"),
    physical_cognitive_some_difficulties = percent_response(physical_cognitive_difficulties_category,.,"some_difficulties_carrying_activities_male_infant"),
    physical_cognitive_alot_difficulties = percent_response(physical_cognitive_difficulties_category,.,"alot_difficulties_carrying_activities_male_infant"),
    physical_cognitive_extreme_difficulties = percent_response(physical_cognitive_difficulties_category,.,"cannot_carry_activities_male_infant"),
    
    type_chronicdisease_1_name = select_percents(type_chronicdisease,1,.,questions,choices,"label"),
    type_chronicdisease_1_count = select_percents(type_chronicdisease,1,.,questions,choices,"count"),
    type_chronicdisease_2_name = select_percents(type_chronicdisease,2,.,questions,choices,"label"),
    type_chronicdisease_2_count = select_percents(type_chronicdisease,2,.,questions,choices,"count"),
    type_chronicdisease_3_name = select_percents(type_chronicdisease,3,.,questions,choices,"label"),
    type_chronicdisease_3_count = select_percents(type_chronicdisease,3,.,questions,choices,"count"),
    type_chronicdisease_4_name = select_percents(type_chronicdisease,4,.,questions,choices,"label"),
    type_chronicdisease_4_count = select_percents(type_chronicdisease,4,.,questions,choices,"count"),
    type_chronicdisease_5_name = select_percents(type_chronicdisease,5,.,questions,choices,"label"),
    type_chronicdisease_5_count = select_percents(type_chronicdisease,5,.,questions,choices,"count"),
    
    barriers_healthcare_lack_docs_overall = meanR(access_healthcare_challenges_reasons.lack_documentation_health,.),
    barriers_healthcare_lack_docs_mena = meanR(filter(.,region_of_origin=="mena")[["access_healthcare_challenges_reasons.lack_documentation_health"]],
                                               filter(.,region_of_origin=="mena"),
                                               group = !!get_group(.)),
    barriers_healthcare_lack_docs_w_c_africa = meanR(filter(.,region_of_origin=="w_c_africa")[["access_healthcare_challenges_reasons.lack_documentation_health"]],
                                               filter(.,region_of_origin=="w_c_africa"),
                                               group = !!get_group(.)),
    barriers_healthcare_lack_docs_e_africa = meanR(filter(.,region_of_origin=="e_africa")[["access_healthcare_challenges_reasons.lack_documentation_health"]],
                                                     filter(.,region_of_origin=="e_africa"),
                                                     group = !!get_group(.)),
    barriers_healthcare_lack_docs_e_africa = meanR(filter(.,region_of_origin=="other")[["access_healthcare_challenges_reasons.lack_documentation_health"]],
                                                   filter(.,region_of_origin=="other"),
                                                   group = !!get_group(.)),
    
    substandard_shelter_type = percent_response(substandard_shelter,.,"yes"),
    
    occupancy_status_owned = percent_response(occupancy_status,.,"ownership"),
    occupancy_status_rented_contract = percent_response(occupancy_status,.,"rental_written_contract"),
    occupancy_status_rented_verbal = percent_response(occupancy_status,.,"rental_verbal_agreement"),
    occupancy_status_provided_employer = percent_response(occupancy_status,.,"housing_provided_employer"),
    occupancy_status_other = percent_response(occupancy_status,.,"other"),
    
    rental_cost_median = medianR(rental_cost,.),
    rental_cost_increased = percent_response(change_rental,.,"increased"),
    access_shelter_challenges_lack_docs = meanR(access_shelter_challenges.dont_have_appropriate_docs,.),
    
    area_accomodation = medianR(total_area_accomodation,.),
    
    occupancy_status_1_name = select_percents(occupancy_status,1,.,questions,choices,"label"),
    occupancy_status_1_pct = select_percents(occupancy_status,1,.,questions,choices,"percent"),
    occupancy_status_2_name = select_percents(occupancy_status,2,.,questions,choices,"label"),
    occupancy_status_2_pct = select_percents(occupancy_status,2,.,questions,choices,"percent"),
    occupancy_status_3_name = select_percents(occupancy_status,3,.,questions,choices,"label"),
    occupancy_status_3_pct = select_percents(occupancy_status,3,.,questions,choices,"percent"),
    occupancy_status_4_name = select_percents(occupancy_status,4,.,questions,choices,"label"),
    occupancy_status_4_pct = select_percents(occupancy_status,4,.,questions,choices,"percent"),
    occupancy_status_5_name = select_percents(occupancy_status,5,.,questions,choices,"label"),
    occupancy_status_5_pct = select_percents(occupancy_status,5,.,questions,choices,"percent"),
    
    shelter_challenges_1_name = select_percents(access_shelter_challenges,1,.,questions,choices,"label"),
    shelter_challenges_1_pct = select_percents(access_shelter_challenges,1,.,questions,choices,"percent"),
    shelter_challenges_2_name = select_percents(access_shelter_challenges,2,.,questions,choices,"label"),
    shelter_challenges_2_pct = select_percents(access_shelter_challenges,2,.,questions,choices,"percent"),
    shelter_challenges_3_name = select_percents(access_shelter_challenges,3,.,questions,choices,"label"),
    shelter_challenges_3_pct = select_percents(access_shelter_challenges,3,.,questions,choices,"percent"),
    
    being_threatened_eviction = percent_response(eviction_threat,.,"yes_threatened_with_eviction"),
    
    shelter_condition_no_damage = percent_response(shelter_condition,.,"no_negligible_damage"),
    shelter_condition_light_damage = percent_response(shelter_condition,.,"light_damage"),
    shelter_condition_medium_damage = percent_response(shelter_condition,.,"medium_damage"),
    shelter_condition_heavy_damage = percent_response(shelter_condition,.,"heavy_damage"),
    shelter_condition_destroyed = percent_response(shelter_condition,.,"shelter_destroyed"),
    
    shelter_concerns_1_name = select_percents(shelter_related_concerns,1,.,questions,choices,"label"),
    shelter_concerns_1_pct = select_percents(shelter_related_concerns,1,.,questions,choices,"percent"),
    shelter_concerns_2_name = select_percents(shelter_related_concerns,2,.,questions,choices,"label"),
    shelter_concerns_2_pct = select_percents(shelter_related_concerns,2,.,questions,choices,"percent"),
    shelter_concerns_3_name = select_percents(shelter_related_concerns,3,.,questions,choices,"label"),
    shelter_concerns_3_pct = select_percents(shelter_related_concerns,3,.,questions,choices,"percent"),
    shelter_concerns_4_name = select_percents(shelter_related_concerns,4,.,questions,choices,"label"),
    shelter_concerns_4_pct = select_percents(shelter_related_concerns,4,.,questions,choices,"percent"),
    shelter_concerns_5_name = select_percents(shelter_related_concerns,5,.,questions,choices,"label"),
    shelter_concerns_5_pct = select_percents(shelter_related_concerns,5,.,questions,choices,"percent"),
    
    nb_respondent_with_schoolaged_children = count_response(hh_with_school_aged_children,.,"yes"),
    nb_school_aged_children= sum(school_aged_boys, na.rm = T) + sum(school_aged_girls, na.rm = T),
    attending_formal_school_overall = sum(children_attending_calc,na.rm = T),
    attending_formal_school_boys = sum(attending_boys_6_10,na.rm = T)+sum(attending_boys_11_17,na.rm = T),
    attending_formal_school_girls = sum(attending_girls_6_10,na.rm = T)+sum(attending_girls_11_17,na.rm = T),
    
    attending_nonformal_school_overall = sum(nonformal_education_boys_calc,na.rm = T)+sum(nonformal_education_girls_calc,na.rm = T),
    attending_nonformal_school_boys = sum(nonformal_education_boys_calc,na.rm = T),
    attending_nonformal_school_girls = sum(nonformal_education_girls_calc,na.rm = T),
    
    nb_children_notattending_notenrolled = sum(notattending_notenrolled_school_male, na.rm = T) + sum(notattending_notenrolled_school_female, na.rm = T),
    noaccess_formal_edu = percent_response(type_education,.,"no_access_formal_edu"),
    attending_formal_edu_overall = sum(total_attending_school,na.rm = T) / sum(school_aged_children,na.rm = T),
    attending_formal_edu_boys = sum(attending_school_male,na.rm = T) / sum(school_aged_boys,na.rm = T),
    attending_formao_edu_girls = sum(attending_school_female,na.rm = T) / sum(school_aged_girls,na.rm = T),
    
    attending_nonformal_edu_overall = (sum(nonformal_education_boys_calc,na.rm = T) + sum(nonformal_education_girls_calc,na.rm = T)) / sum(school_aged_children,na.rm = T),
    attending_nonformal_edu_boys = sum(nonformal_education_boys_calc,na.rm = T) / sum(school_aged_boys,na.rm = T),
    attending_nonformal_edu_girls = sum(nonformal_education_girls_calc,na.rm = T) / sum(school_aged_girls,na.rm = T),
    
    reasons_notattendind_school_1_name = select_percents(reasons_not_enrolled_not_attending,1,.,questions,choices,"label"),
    reasons_notattendind_school_1_count = select_percents(reasons_not_enrolled_not_attending,1,.,questions,choices,"count"),
    reasons_notattendind_school_2_name = select_percents(reasons_not_enrolled_not_attending,2,.,questions,choices,"label"),
    reasons_notattendind_school_2_count = select_percents(reasons_not_enrolled_not_attending,2,.,questions,choices,"count"),
    reasons_notattendind_school_3_name = select_percents(reasons_not_enrolled_not_attending,3,.,questions,choices,"label"),
    reasons_notattendind_school_3_count = select_percents(reasons_not_enrolled_not_attending,3,.,questions,choices,"count"),
    reasons_notattendind_school_4_name = select_percents(reasons_not_enrolled_not_attending,4,.,questions,choices,"label"),
    reasons_notattendind_school_4_count = select_percents(reasons_not_enrolled_not_attending,4,.,questions,choices,"count"),
    reasons_notattendind_school_5_name = select_percents(reasons_not_enrolled_not_attending,5,.,questions,choices,"label"),
    reasons_notattendind_school_5_count = select_percents(reasons_not_enrolled_not_attending,5,.,questions,choices,"count"),
   
    related_education_expenses = sum(education_related_expenditure_exc_0,na.rm = T) / sum(total_expenditures_exc_0),
    median_monthly_edu_expenses = medianR(education_related_expenditure_exc_0,.),
    
    difficulties_obtaining_cash = percent_response(obtaining_cash_challenges,.,"yes"),
    facing_barriers_acccess_marketplace = percent_response(facing_barriers_acccess_marketplace,.,"yes"),
    
    unable_obtain_enough_cash_1_name = select_percents(obtaining_cash_challenge_reasons,1,.,questions,choices,"label"),  
    unable_obtain_enough_cash_1_pct = select_percents(obtaining_cash_challenge_reasons,1,.,questions,choices,"percent"),
    unable_obtain_enough_cash_2_name = select_percents(obtaining_cash_challenge_reasons,2,.,questions,choices,"label"),  
    unable_obtain_enough_cash_2_pct = select_percents(obtaining_cash_challenge_reasons,2,.,questions,choices,"percent"),
    unable_obtain_enough_cash_3_name = select_percents(obtaining_cash_challenge_reasons,3,.,questions,choices,"label"),  
    unable_obtain_enough_cash_3_pct = select_percents(obtaining_cash_challenge_reasons,3,.,questions,choices,"percent"),
    unable_obtain_enough_cash_4_name = select_percents(obtaining_cash_challenge_reasons,4,.,questions,choices,"label"),  
    unable_obtain_enough_cash_4_pct = select_percents(obtaining_cash_challenge_reasons,4,.,questions,choices,"percent"),
    
    barrier_access_marketplace_1_name = select_percents(barriers_access_market,1,.,questions,choices,"label"),  
    barrier_access_marketplace_1_pct = select_percents(barriers_access_market,1,.,questions,choices,"percent"),
    barrier_access_marketplace_2_name = select_percents(barriers_access_market,2,.,questions,choices,"label"),  
    barrier_access_marketplace_2_pct = select_percents(barriers_access_market,2,.,questions,choices,"percent"),
    barrier_access_marketplace_3_name = select_percents(barriers_access_market,3,.,questions,choices,"label"),  
    barrier_access_marketplace_3_pct = select_percents(barriers_access_market,3,.,questions,choices,"percent"),
    barrier_access_marketplace_4_name = select_percents(barriers_access_market,4,.,questions,choices,"label"),  
    barrier_access_marketplace_4_pct = select_percents(barriers_access_market,4,.,questions,choices,"percent"),
    
    unemployed_prop = sum(type_jobs.didnt_work,na.rm = T)/(sum(nb_adults_female,na.rm = T)+sum(nb_adults_male,na.rm = T)),
    permanent_job_prop = sum(type_jobs.permanent_job,na.rm = T)/(sum(nb_adults_female,na.rm = T)+sum(nb_adults_male,na.rm = T)),
    temporary_job_prop = sum(type_jobs.temporary_job,na.rm = T)/(sum(nb_adults_female,na.rm = T)+sum(nb_adults_male,na.rm = T)),
    daily_labour_job_prop = sum(type_jobs.daily_labour,na.rm = T)/(sum(nb_adults_female,na.rm = T)+sum(nb_adults_male,na.rm = T)),
    other_job_prop = sum(type_jobs.other,na.rm = T)/(sum(nb_adults_female,na.rm = T)+sum(nb_adults_male,na.rm = T)),
    
    travel_market_15min = percent_response(travel_to_market,.,"less_15min"),
    travel_market_15_29min = percent_response(travel_to_market,.,"between_15_29min"),
    travel_market_more_30min = percent_response(travel_to_market,.,"between_30_59min")+
                               percent_response(travel_to_market,.,"between_1_2hours")+
                               percent_response(travel_to_market,.,"more_2hours"),
    
    feeling_indanger = percent_response(feeling_danger,.,"yes"),
    
    feeling_indanger_1_name = select_percents(insecurity_factors,1,.,questions,choices,"label"),
    feeling_indanger_1_pct = select_percents(insecurity_factors,1,.,questions,choices,"percent"),
    feeling_indanger_2_name = select_percents(insecurity_factors,2,.,questions,choices,"label"),
    feeling_indanger_2_pct = select_percents(insecurity_factors,2,.,questions,choices,"percent"),
    feeling_indanger_3_name = select_percents(insecurity_factors,3,.,questions,choices,"label"),
    feeling_indanger_3_pct = select_percents(insecurity_factors,3,.,questions,choices,"percent"),
    feeling_indanger_4_name = select_percents(insecurity_factors,4,.,questions,choices,"label"),
    feeling_indanger_4_pct = select_percents(insecurity_factors,4,.,questions,choices,"percent"),
    feeling_indanger_5_name = select_percents(insecurity_factors,5,.,questions,choices,"label"),
    feeling_indanger_5_pct = select_percents(insecurity_factors,5,.,questions,choices,"percent"),
    
    
    feeling_safer_1_name = select_percents(safety_factors,1,.,questions,choices,"label"),
    feeling_safer_1_pct = select_percents(safety_factors,1,.,questions,choices,"percent"),
    feeling_safer_2_name = select_percents(safety_factors,2,.,questions,choices,"label"),
    feeling_safer_2_pct = select_percents(safety_factors,2,.,questions,choices,"percent"),
    feeling_safer_3_name = select_percents(safety_factors,3,.,questions,choices,"label"),
    feeling_safer_3_pct = select_percents(safety_factors,3,.,questions,choices,"percent"),
    feeling_safer_4_name = select_percents(safety_factors,4,.,questions,choices,"label"),
    feeling_safer_4_pct = select_percents(safety_factors,4,.,questions,choices,"percent"),
    feeling_safer_5_name = select_percents(safety_factors,5,.,questions,choices,"label"),
    feeling_safer_5_pct = select_percents(safety_factors,5,.,questions,choices,"percent"),
    
    children_safety_concers_1_name = select_percents(witnessed_insecurity_factors_children,1,.,questions,choices,"label"),
    children_safety_concers_1_pct = select_percents(witnessed_insecurity_factors_children,1,.,questions,choices,"percent"),
    children_safety_concers_2_name = select_percents(witnessed_insecurity_factors_children,2,.,questions,choices,"label"),
    children_safety_concers_2_pct = select_percents(witnessed_insecurity_factors_children,2,.,questions,choices,"percent"),
    children_safety_concers_3_name = select_percents(witnessed_insecurity_factors_children,3,.,questions,choices,"label"),
    children_safety_concers_3_pct = select_percents(witnessed_insecurity_factors_children,3,.,questions,choices,"percent"),
    children_safety_concers_4_name = select_percents(witnessed_insecurity_factors_children,4,.,questions,choices,"label"),
    children_safety_concers_4_pct = select_percents(witnessed_insecurity_factors_children,4,.,questions,choices,"percent"),
    children_safety_concers_5_name = select_percents(witnessed_insecurity_factors_children,5,.,questions,choices,"label"),
    children_safety_concers_5_pct = select_percents(witnessed_insecurity_factors_children,5,.,questions,choices,"percent"),
    
    children_working = percent_response(children_labour,.,"yes"),
    
    no_coping_strategy_avoiding_risks = percent_response(protection_coping,.,"nothing_ican_do"),
    
    protection_coping_1_name = select_percents(protection_coping,1,.,questions,choices,"label"),
    protection_coping_1_pct = select_percents(protection_coping,1,.,questions,choices,"percent"),
    protection_coping_2_name = select_percents(protection_coping,2,.,questions,choices,"label"),
    protection_coping_2_pct = select_percents(protection_coping,2,.,questions,choices,"percent"),
    protection_coping_3_name = select_percents(protection_coping,3,.,questions,choices,"label"),
    protection_coping_3_pct = select_percents(protection_coping,3,.,questions,choices,"percent"),
    protection_coping_4_name = select_percents(protection_coping,4,.,questions,choices,"label"),
    protection_coping_4_pct = select_percents(protection_coping,4,.,questions,choices,"percent"),
    protection_coping_5_name = select_percents(protection_coping,5,.,questions,choices,"label"),
    protection_coping_5_pct = select_percents(protection_coping,5,.,questions,choices,"percent"),
    
    unable_move_around = percent_response(freedom_movement,.,"no"),
    
    lack_freedom_movement_1_name = select_percents(restricted_freedom_movement_reasons,1,.,questions,choices,"label"),
    lack_freedom_movement_1_pct = select_percents(restricted_freedom_movement_reasons,1,.,questions,choices,"percent"),
    lack_freedom_movement_2_name = select_percents(restricted_freedom_movement_reasons,2,.,questions,choices,"label"),
    lack_freedom_movement_2_pct = select_percents(restricted_freedom_movement_reasons,2,.,questions,choices,"percent"),
    lack_freedom_movement_3_name = select_percents(restricted_freedom_movement_reasons,3,.,questions,choices,"label"),
    lack_freedom_movement_3_pct = select_percents(restricted_freedom_movement_reasons,3,.,questions,choices,"percent"),
    lack_freedom_movement_4_name = select_percents(restricted_freedom_movement_reasons,4,.,questions,choices,"label"),
    lack_freedom_movement_4_pct = select_percents(restricted_freedom_movement_reasons,4,.,questions,choices,"percent"),
    
    uxo_awareness = percent_response(presence_explosive_hazards,.,"yes"),
    
    fearing_arrest_lack_doc = meanR(insecurity_factors.afraid_being_arrested_lack_docs,.),
    
    migrant_intention_stay_current_location = percent_response(migration_intention,.,"stay_current_location_lby"),
    migrant_intention_stay_move_location = percent_response(migration_intention,.,"move_another_location_lby"),
    migrant_intention_stay_leave_lby = percent_response(migration_intention,.,"leave_lby"),
    
    migrant_destination_eu = percent_response(destination_after_lby,.,"europe_destination"),
    migrant_destination_homecountry = percent_response(destination_after_lby,.,"return_homecountry_destination"),
    migrant_destination_african_country = percent_response(destination_after_lby,.,"another_african_country_destnation"),
    migrant_destination_elsewhere = percent_response(destination_after_lby,.,"elsewhere"),
    
    migrant_intention_motivation_1_name = select_percents(migration_intention_reasons,1,.,questions,choices,"label"),
    migrant_intention_motivation_1_pct = select_percents(migration_intention_reasons,1,.,questions,choices,"percent"),
    migrant_intention_motivation_2_name = select_percents(migration_intention_reasons,2,.,questions,choices,"label"),
    migrant_intention_motivation_2_pct = select_percents(migration_intention_reasons,2,.,questions,choices,"percent"),
    migrant_intention_motivation_3_name = select_percents(migration_intention_reasons,3,.,questions,choices,"label"),
    migrant_intention_motivation_3_pct = select_percents(migration_intention_reasons,3,.,questions,choices,"percent"),
    
    priority_needs_1_name = select_percents(priority_assistance_needs,1,.,questions,choices,"label"),
    priority_needs_1_pct = select_percents(priority_assistance_needs,1,.,questions,choices,"percent"),
    priority_needs_2_name = select_percents(priority_assistance_needs,2,.,questions,choices,"label"),
    priority_needs_2_pct = select_percents(priority_assistance_needs,2,.,questions,choices,"percent"),
    priority_needs_3_name = select_percents(priority_assistance_needs,3,.,questions,choices,"label"),
    priority_needs_3_pct = select_percents(priority_assistance_needs,3,.,questions,choices,"percent"),
    priority_needs_4_name = select_percents(priority_assistance_needs,4,.,questions,choices,"label"),
    priority_needs_4_pct = select_percents(priority_assistance_needs,4,.,questions,choices,"percent"),
    priority_needs_5_name = select_percents(priority_assistance_needs,5,.,questions,choices,"label"),
    priority_needs_5_pct = select_percents(priority_assistance_needs,5,.,questions,choices,"percent")
  )
    
  
  write.csv(dm_mantika_data,"../final_analysis/datamerge/mantika_26112019.csv")
  